Improve git commit hash check in workflow
Updated git commit hash check with additional error handling.

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -33,18 +33,18 @@ jobs:
         run: |
           echo "编译前/mnt剩余空间: $(df -h | grep '/mnt' | awk '{print $4}')"
 
-      - name: 安装依赖
-        run: |
-          sudo apt update -y
-          sudo apt full-upgrade -y
-          sudo apt install git -y
-          # sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
-          # bzip2 ccache clang cmake cpio curl device-tree-compiler flex gawk gcc-multilib g++-multilib gettext \
-          # genisoimage git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev \
-          # libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev \
-          # libreadline-dev libssl-dev libtool llvm lrzsz libnsl-dev ninja-build p7zip p7zip-full patch pkgconf \
-          # python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion \
-          # swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
+      # - name: 安装依赖
+      #   run: |
+      #     sudo apt update -y
+      #     sudo apt full-upgrade -y
+      #     sudo apt install git -y
+      #     sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
+      #     bzip2 ccache clang cmake cpio curl device-tree-compiler flex gawk gcc-multilib g++-multilib gettext \
+      #     genisoimage git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev \
+      #     libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev \
+      #     libreadline-dev libssl-dev libtool llvm lrzsz libnsl-dev ninja-build p7zip p7zip-full patch pkgconf \
+      #     python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion \
+      #     swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
       
       - name: 检出LEDE仓库
         uses: actions/checkout@main
@@ -52,7 +52,9 @@ jobs:
           repository: coolsnowwolf/lede
 
       - name: Check git commit hash
-        run: git rev-parse --short HEAD || echo "GIT FAILED"
+        run: |
+          git rev-parse --short HEAD || echo "GIT FAILED 1"
+          git rev-parse --git-dir >/dev/null 2>&1 || echo "GIT FAILED 2"
 
       - name: 创建工作目录
         run: |
@@ -64,7 +66,9 @@ jobs:
           mv ./* $WD
 
       - name: Check git commit hash
-        run: git rev-parse --short HEAD || echo "GIT FAILED"
+        run: |
+          git rev-parse --short HEAD || echo "GIT FAILED 1"
+          git rev-parse --git-dir >/dev/null 2>&1 || echo "GIT FAILED 2"
 
       # - name: 修改编译有关配置
       #   run: |
