Refactor CI workflow by commenting out steps
Comment out several installation and build steps in the CI workflow.

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -37,18 +37,22 @@ jobs:
         run: |
           sudo apt update -y
           sudo apt full-upgrade -y
-          sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
-          bzip2 ccache clang cmake cpio curl device-tree-compiler flex gawk gcc-multilib g++-multilib gettext \
-          genisoimage git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev \
-          libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev \
-          libreadline-dev libssl-dev libtool llvm lrzsz libnsl-dev ninja-build p7zip p7zip-full patch pkgconf \
-          python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion \
-          swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
+          sudo apt install git -y
+          # sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
+          # bzip2 ccache clang cmake cpio curl device-tree-compiler flex gawk gcc-multilib g++-multilib gettext \
+          # genisoimage git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev \
+          # libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev \
+          # libreadline-dev libssl-dev libtool llvm lrzsz libnsl-dev ninja-build p7zip p7zip-full patch pkgconf \
+          # python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion \
+          # swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
       
       - name: 检出LEDE仓库
         uses: actions/checkout@main
         with:
           repository: coolsnowwolf/lede
+
+      - name: Check git commit hash
+        run: git rev-parse --short HEAD || echo "GIT FAILED"
 
       - name: 创建工作目录
         run: |
@@ -59,70 +63,73 @@ jobs:
         run: |
           mv ./* $WD
 
-      - name: 修改编译有关配置
-        run: |
-          sed -i 's/#src-git helloworld/src-git helloworld/g' ./feeds.conf.default
-          ./scripts/feeds update -a
-          ./scripts/feeds install -a
-          curl https://raw.githubusercontent.com/cricketbrother/lede-actions/refs/heads/main/my.config -o .config
-          make defconfig
-        working-directory: ${{ env.WD }}
-        
-      - name: 下载编译依赖
-        run: |
-          make download -j$(nproc) || make download -j1 || make download -j1 V=s
-        working-directory: ${{ env.WD }}
+- name: Check git commit hash
+  run: git rev-parse --short HEAD || echo "GIT FAILED"
 
-      - name: 编译固件
-        run: |
-          make -j$(nproc) || make -j1 || make -j1 V=s
-        working-directory: ${{ env.WD }}
-
-      - name: 生成TAG
-        id: tag
-        run: |
-          today=$(date +v%Y.%m.%d)
-          lede_version=$(cat package/lean/default-settings/files/zzz-default-settings | egrep -m 1 -o 'R[0-9]{2}\.[0-9]{1,2}\.[0-9]{1,2}')
-          tag=$lede_version-$today-test
-          echo "tag=$tag" >> $GITHUB_OUTPUT
-        working-directory: ${{ env.WD }}
+      # - name: 修改编译有关配置
+      #   run: |
+      #     sed -i 's/#src-git helloworld/src-git helloworld/g' ./feeds.conf.default
+      #     ./scripts/feeds update -a
+      #     ./scripts/feeds install -a
+      #     curl https://raw.githubusercontent.com/cricketbrother/lede-actions/refs/heads/main/my.config -o .config
+      #     make defconfig
+      #   working-directory: ${{ env.WD }}
         
-      - name: 重命名固件
-        run: |
-          cp .config ./bin/targets/x86/64/${{ steps.tag.outputs.tag }}.config
-          for file in $(ls ./bin/targets/x86/64/lede*); do
-            if [[ -d "$file" ]]; then
-                continue
-            fi
-            newfile=${file%generic*}generic-${{ steps.tag.outputs.tag }}${file##*generic}
-            mv "$file" "$newfile"
-          done
-        working-directory: ${{ env.WD }}
+      # - name: 下载编译依赖
+      #   run: |
+      #     make download -j$(nproc) || make download -j1 || make download -j1 V=s
+      #   working-directory: ${{ env.WD }}
+
+      # - name: 编译固件
+      #   run: |
+      #     make -j$(nproc) || make -j1 || make -j1 V=s
+      #   working-directory: ${{ env.WD }}
+
+      # - name: 生成TAG
+      #   id: tag
+      #   run: |
+      #     today=$(date +v%Y.%m.%d)
+      #     lede_version=$(cat package/lean/default-settings/files/zzz-default-settings | egrep -m 1 -o 'R[0-9]{2}\.[0-9]{1,2}\.[0-9]{1,2}')
+      #     tag=$lede_version-$today-test
+      #     echo "tag=$tag" >> $GITHUB_OUTPUT
+      #   working-directory: ${{ env.WD }}
+        
+      # - name: 重命名固件
+      #   run: |
+      #     cp .config ./bin/targets/x86/64/${{ steps.tag.outputs.tag }}.config
+      #     for file in $(ls ./bin/targets/x86/64/lede*); do
+      #       if [[ -d "$file" ]]; then
+      #           continue
+      #       fi
+      #       newfile=${file%generic*}generic-${{ steps.tag.outputs.tag }}${file##*generic}
+      #       mv "$file" "$newfile"
+      #     done
+      #   working-directory: ${{ env.WD }}
 
       - name: 获取编译后/mnt剩余空间
         run: |
           echo "编译前/mnt剩余空间: $(df -h | grep '/mnt' | awk '{print $4}')"
 
-      - name: 随机获取一句诗词
-        id: poem
-        run: |
-          sudo apt update
-          sudo apt install jq
-          response=$(curl --user-agent "Mozilla/5.0" https://api.codelife.cc/todayShici?lang=cn)
-          quotes=$(echo $response | jq -r '.data.quotes')
-          author=$(echo $response | jq -r '.data.author')
-          dynasty=$(echo $response | jq -r '.data.dynasty')
-          title=$(echo $response | jq -r '.data.title')
-          poem=$quotes"    "——" "$dynasty" "·" "$author《$title》
-          echo "poem=$poem" >> $GITHUB_OUTPUT
+      # - name: 随机获取一句诗词
+      #   id: poem
+      #   run: |
+      #     sudo apt update
+      #     sudo apt install jq
+      #     response=$(curl --user-agent "Mozilla/5.0" https://api.codelife.cc/todayShici?lang=cn)
+      #     quotes=$(echo $response | jq -r '.data.quotes')
+      #     author=$(echo $response | jq -r '.data.author')
+      #     dynasty=$(echo $response | jq -r '.data.dynasty')
+      #     title=$(echo $response | jq -r '.data.title')
+      #     poem=$quotes"    "——" "$dynasty" "·" "$author《$title》
+      #     echo "poem=$poem" >> $GITHUB_OUTPUT
           
-      - name: 上传发行版
-        uses: softprops/action-gh-release@master
-        with:
-          files: |
-            ${{ env.WD }}/bin/targets/x86/64/*
-          tag_name: ${{ steps.tag.outputs.tag }}
-          draft: false
-          prerelease: false
-          body: |
-            ${{ steps.poem.outputs.poem }}
+      # - name: 上传发行版
+      #   uses: softprops/action-gh-release@master
+      #   with:
+      #     files: |
+      #       ${{ env.WD }}/bin/targets/x86/64/*
+      #     tag_name: ${{ steps.tag.outputs.tag }}
+      #     draft: false
+      #     prerelease: false
+      #     body: |
+      #       ${{ steps.poem.outputs.poem }}
